### ISSUE TITLE
[RFC] [pub-page-title-action]

### ISSUE THREAD

**Issue by simon-debruijn** [cultuurnet/udb3-frontend#80]
## Use case

When a title contains a action like 'toevoegen', this component makes it have the correct styling.

## Existing examples in the Legacy UI and/or Vue app

![Schermafbeelding 2020-09-21 om 13 50 35](https://user-images.githubusercontent.com/66943525/93763486-d2d46580-fc11-11ea-81fa-45b1fab35c1b.png)

## Proposed styling

Wrap the content in a `small html tag` and apply `text-transform: lowercase`. 

## Actions

`@click`

**Comment by bertramakers** [comment]
Good idea. Will it use `pub-link` underneath?
Can you also add a code block with an example of how to use it in combination with `pub-page-title`?

**Comment by simon-debruijn** [comment]
That was the thing I wasn't sure about yet. Maybe leave it separate and just have:
`<pub-page-title-action>
      <pub-link as="nuxt-link" to="productions/create">
          toevoegen
      </ pub-link>
</ pub-page-title-action>
`
the 'to' and 'as' props will probably make it unnecessarily complicated if we have to pass them through

**Comment by bertramakers** [comment]
Okay yeah seeing it like that I agree. It would also give some more flexibility, so we could also have a `<pub-page-title-action>` with another component inside with a `@click` to e.g. open a modal or something like that instead of a `pub-link` to another page.

**Comment by bertramakers** [comment]
So it would work like this?

```
<pub-page-title>
    Producties
    <pub-page-title-action>
        <pub-link as="nuxt-link" to="productions/create">toevoegen</ pub-link>
    </pub-page-title-action>
</pub-page-title>
```

**Comment by simon-debruijn** [comment]
> So it would work like this?
> 
> ```
> <pub-page-title>
>     Producties
>     <pub-page-title-action>
>         <pub-link as="nuxt-link" to="productions/create">toevoegen</ pub-link>
>     </pub-page-title-action>
> </pub-page-title>
> ```

Yes, sorry I was struggling with the spacing in markdown for the codeblocks 😋 But that is exactly how it would be

**Comment by bertramakers** [comment]
It's a lot of tags but gives more flexibility about what the action can be (a link, @click, etc) and have that separated from the styling so I'm okay with that trade-off. @geoffreydhuyvetters do you have some input or do we implement it like this?
