### ISSUE TITLE
[RFC] component primitives

### ISSUE THREAD

**Issue by geoffreydhuyvetters** [cultuurnet/udb3-frontend#94]
In every design system we need components that make it easier to create compositions, this issue will open up a discussion on this.

**Grouping elements**

https://bradfrost.com/blog/post/atomic-web-design/\

https://vueds.com/example/#/Elements
https://vueds.com/example/#/Patterns

**elements / patterns** 

- an element is the smallest basic structure you can reuse
- a pattern consists of multiple elements

**atoms / molecules / organisms / templates / pages**

not everything makes as much sense in the context of a design system, but we could take cues from it

- atoms = elements
- molecules = patterns
- organisms = section of an interface (page header with line and navigation)
- templates = groups of organisms (list template)

We could use slots for this?

not a component

- page = filled in template (events list)

**Box / Block / Element**

- basic component 
- exposes properties that every component owns

**Stack** 

- stack components on top of each other
- set spacing (inner)

**Inline**

- position components next to each other
- set spacing (inner)

**Grid**

- exposes properties from the CSS grid spec
- spacing = gutter

**Comment by geoffreydhuyvetters** [comment]
```js

<Stack>
	<Label></Label>
	<Stack>
		<Inline>
			<Icon/>
			<Input>
		</Inline>
		<Erorr></Error>
	<Stack>
</Stack>


```

**Comment by simon-debruijn** [comment]
The documentation you've written so far looks good and seems a good way to move forward! I'm only wondering, what you mean by `We could use slots for this?` what is `this`?

**Comment by geoffreydhuyvetters** [comment]
> I'm only wondering, what you mean by We could use slots for this? what is this?

Creating a template and filling in the places with real content. Provide an 'empty' placeholder component and use different slots to fill in the placeholders.
